services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      .env
    depends_on:
      - db
      - redis
      - minio
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres-file-storage
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5431:5432"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-sessions
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: s3-minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address :9001
    networks:
      - app-network


networks:
  app-network:
    name: app-network
    driver: bridge


