spring:

  web:
    resources:
      add-mappings: false

  application:
    name: file-storage-api

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect

minio:
  rootBucket: ${ROOT_BUCKET}
  url: ${MINIO_URL}
  credentials:
    accessKey: ${MINIO_ACCESS_KEY}
    secretKey: ${MINIO_SECRET_KEY}

redis:
  host: localhost
  port: 6379